FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY ./website/package.json ./
COPY ./website/package-lock.json ./

# Install dependencies with verbose logging
RUN npm install --loglevel verbose

EXPOSE 3000

CMD ["npm", "run", "dev"] 